title: Embedded Systems & Electronics Lab
description: A structured 90-day embedded systems learning program.
markdown: kramdown

kramdown:
  math_engine: mathjax
  input: GFM

theme: jekyll-theme-primer

plugins:
  - jekyll-remote-theme
